name: Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.x"
    - name: Install PDM
      run: >-
        python -m
        pip install
        pdm
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        pdm build
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
